import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import InPageNavigation from "./InPageNavigation";

function MatchDetail() {
  let { id } = useParams();

  let fixeddata = {
    matchInfo: {
      matchId: 45921,
      matchDescription: "8th Match",
      matchFormat: "T20",
      matchType: "league",
      complete: true,
      domestic: false,
      matchStartTimestamp: 1648821600000,
      matchCompleteTimestamp: 1648834200000,
      dayNight: true,
      year: 2022,
      dayNumber: 1,
      state: "complete",
      team1: {
        id: 63,
        name: "Kolkata Knight Riders",
        playerDetails: [
          {
            id: 1447,
            name: "Rahane",
            fullName: "Ajinkya Rahane",
            nickName: "Rahane",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 171082,
          },
          {
            id: 10917,
            name: "Venkatesh Iyer",
            fullName: "Venkatesh Iyer",
            nickName: "Venkatesh Iyer",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 226278,
          },
          {
            id: 9428,
            name: "Shreyas Iyer",
            fullName: "Shreyas Iyer",
            nickName: "Shreyas Iyer",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 171024,
          },
          {
            id: 9204,
            name: "Nitish Rana",
            fullName: "Nitish Rana",
            nickName: "Nitish Rana",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 171047,
          },
          {
            id: 7990,
            name: "Billings",
            fullName: "Sam Billings",
            nickName: "Billings",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Kolkata Knight Riders",
            faceImageId: 156173,
          },
          {
            id: 7736,
            name: "Russell",
            fullName: "Andre Russell",
            nickName: "Russell",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170821,
          },
          {
            id: 2276,
            name: "Narine",
            fullName: "Sunil Narine",
            nickName: "Narine",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 152654,
          },
          {
            id: 1057,
            name: "Southee",
            fullName: "Tim Southee",
            nickName: "Southee",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170753,
          },
          {
            id: 12345,
            name: "Shivam Mavi",
            fullName: "Shivam Mavi",
            nickName: "Shivam Mavi",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 155147,
          },
          {
            id: 1858,
            name: "Umesh",
            fullName: "Umesh Yadav",
            nickName: "Umesh Yadav",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Kolkata Knight Riders",
            faceImageId: 153874,
          },
          {
            id: 12926,
            name: "Chakaravarthy",
            fullName: "Varun Chakaravarthy",
            nickName: "Chakaravarthy",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 226220,
          },
          {
            id: 3007,
            name: "Nabi",
            fullName: "Mohammad Nabi",
            nickName: "Nabi",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170853,
          },
          {
            id: 9500,
            name: "C Karunaratne",
            fullName: "Chamika Karunaratne",
            nickName: "Karunaratne",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 216499,
          },
          {
            id: 9624,
            name: "Indrajith",
            fullName: "Baba Indrajith",
            nickName: "Indrajith",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 226621,
          },
          {
            id: 10896,
            name: "Rinku Singh",
            fullName: "Rinku Singh",
            nickName: "Rinku Singh",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 187877,
          },
          {
            id: 12344,
            name: "Anukul Roy",
            fullName: "Anukul Roy",
            nickName: "Anukul Roy",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Kolkata Knight Riders",
            faceImageId: 153915,
          },
          {
            id: 12640,
            name: "Pratham Singh",
            fullName: "Pratham Singh",
            nickName: "Pratham Singh",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 12813,
            name: "Abhijeet Tomar",
            fullName: "Abhijeet Tomar",
            nickName: "Abhijeet Tomar",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 14274,
            name: "Rasikh Salam",
            fullName: "Rasikh Salam",
            nickName: "Rasikh Salam",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 19473,
            name: "Aman Hakim Khan",
            fullName: "Aman Hakim Khan",
            nickName: "Aman Hakim Khan",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 24261,
            name: "Ashok Sharma",
            fullName: "Ashok Sharma",
            nickName: "Ashok Sharma",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 24281,
            name: "Ramesh Kumar",
            fullName: "Ramesh Kumar",
            nickName: "Ramesh Kumar",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 8846,
            name: "Jackson",
            fullName: "Sheldon Jackson",
            nickName: "Jackson",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Kolkata Knight Riders",
            faceImageId: 169694,
          },
        ],
        shortName: "KKR",
      },
      team2: {
        id: 65,
        name: "Punjab Kings",
        playerDetails: [
          {
            id: 2195,
            name: "Mayank Agarwal",
            fullName: "Mayank Agarwal",
            nickName: "Mayank",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Punjab Kings",
            faceImageId: 171091,
          },
          {
            id: 1446,
            name: "Dhawan",
            fullName: "Shikhar Dhawan",
            nickName: "Dhawan",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Punjab Kings",
            faceImageId: 170660,
          },
          {
            id: 10045,
            name: "Livingstone",
            fullName: "Liam Livingstone",
            nickName: "Livingstone",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Punjab Kings",
            faceImageId: 171085,
          },
          {
            id: 7869,
            name: "B Rajapaksa",
            fullName: "Bhanuka Rajapaksa",
            nickName: "Rajapaksa",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 216502,
          },
          {
            id: 11215,
            name: "Odean Smith",
            fullName: "Odean Smith",
            nickName: "Odean Smith",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 226368,
          },
          {
            id: 10226,
            name: "Shahrukh Khan",
            fullName: "Shahrukh Khan",
            nickName: "Shahrukh Khan",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Punjab Kings",
            faceImageId: 226465,
          },
          {
            id: 14452,
            name: "Harpreet Brar",
            fullName: "Harpreet Brar",
            nickName: "Harpreet Brar",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Punjab Kings",
            faceImageId: 226471,
          },
          {
            id: 22601,
            name: "Raj Bawa",
            fullName: "Raj Bawa",
            nickName: "Raj Bawa",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 226295,
          },
          {
            id: 9585,
            name: "Rabada",
            fullName: "Kagiso Rabada",
            nickName: "Rabada",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Punjab Kings",
            faceImageId: 170759,
          },
          {
            id: 13217,
            name: "Arshdeep Singh",
            fullName: "Arshdeep Singh",
            nickName: "Arshdeep Singh",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm fast-medium",
            teamName: "Punjab Kings",
            faceImageId: 151715,
          },
          {
            id: 12087,
            name: "Rahul Chahar",
            fullName: "Rahul Chahar",
            nickName: "Rahul Chahar",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Punjab Kings",
            faceImageId: 226225,
          },
          {
            id: 14254,
            name: "Prabhsimran",
            fullName: "Prabhsimran Singh",
            nickName: "Prabhsimran",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Punjab Kings",
            faceImageId: 226515,
          },
          {
            id: 8616,
            name: "Rishi Dhawan",
            fullName: "Rishi Dhawan",
            nickName: "Rishi Dhawan",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Punjab Kings",
            faceImageId: 151723,
          },
          {
            id: 6641,
            name: "Howell",
            fullName: "Benny Howell",
            nickName: "Benny Howell",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 226305,
          },
          {
            id: 11404,
            name: "Ishan Porel",
            fullName: "Ishan Porel",
            nickName: "Ishan Porel",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 226312,
          },
          {
            id: 15861,
            name: "Vaibhav Arora",
            fullName: "Vaibhav Arora",
            nickName: "Vaibhav Arora",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Punjab Kings",
            faceImageId: 182026,
          },
          {
            id: 19262,
            name: "Ansh Patel",
            fullName: "Ansh Patel",
            nickName: "Ansh Patel",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Punjab Kings",
            faceImageId: 182026,
          },
          {
            id: 13914,
            name: "Atharva Taide",
            fullName: "Atharva Taide",
            nickName: "Atharva Taide",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Punjab Kings",
            faceImageId: 182026,
          },
          {
            id: 11054,
            name: "Prerak Mankad",
            fullName: "Prerak Mankad",
            nickName: "Prerak Mankad",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 169684,
          },
          {
            id: 10214,
            name: "Jitesh Sharma",
            fullName: "Jitesh Sharma",
            nickName: "Jitesh Sharma",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Punjab Kings",
            faceImageId: 226474,
          },
          {
            id: 9717,
            name: "Writtick Chatterjee",
            fullName: "Writtick Chatterjee",
            nickName: "Writtick Chatterjee",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Punjab Kings",
            faceImageId: 182026,
          },
          {
            id: 8962,
            name: "Baltej Singh",
            fullName: "Baltej Singh",
            nickName: "Baltej Singh",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Punjab Kings",
            faceImageId: 182026,
          },
          {
            id: 8356,
            name: "Sandeep Sharma",
            fullName: "Sandeep Sharma",
            nickName: "Sandeep Sharma",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 65,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Punjab Kings",
            faceImageId: 153909,
          },
        ],
        shortName: "PBKS",
      },
      series: {
        id: 4061,
        name: "Indian Premier League 2022",
        seriesType: "IPL",
        startDate: 1648821600000,
        endDate: 1648834200000,
        seriesFolder: "2022_IPL",
        odiSeriesResult: "",
        t20SeriesResult: "",
        testSeriesResult: "",
        tournament: true,
      },
      umpire1: {
        id: 8297,
        name: "Anil Kumar Chaudhary",
        country: "IND",
      },
      umpire2: {
        id: 9680,
        name: "Saiyed Khalid",
        country: "IND",
      },
      umpire3: {
        id: 8905,
        name: "Jayaraman Madanagopal",
        country: "IND",
      },
      referee: {
        id: 9225,
        name: "Prakash Bhatt",
        country: "IND",
      },
      tossResults: {},
      result: {
        resultType: "win",
        winningTeam: "Kolkata Knight Riders",
        winningteamId: 63,
        winningMargin: 6,
        winByRuns: false,
        winByInnings: false,
      },
      venue: {
        id: 81,
        name: "Wankhede Stadium",
        city: "Mumbai",
        country: "India",
        timezone: "",
        latitude: "",
        longitude: "",
      },
      status: "Kolkata Knight Riders won by 6 wkts",
      playersOfTheMatch: [
        {
          id: 1858,
          name: "Umesh",
          fullName: "Umesh Yadav",
          nickName: "Umesh Yadav",
          captain: false,
          role: "Batsman",
          keeper: false,
          substitute: false,
          teamId: 0,
          battingStyle: " ",
          bowlingStyle: " ",
          teamName: " ",
          faceImageId: 153874,
        },
      ],
      playersOfTheSeries: [],
      revisedTarget: {},
      matchTeamInfo: [
        {
          battingTeamId: 65,
          battingTeamShortName: "PBKS",
          bowlingTeamId: 63,
          bowlingTeamShortName: "KKR",
        },
        {
          battingTeamId: 63,
          battingTeamShortName: "KKR",
          bowlingTeamId: 65,
          bowlingTeamShortName: "PBKS",
        },
      ],
      isMatchNotCovered: false,
      HYSEnabled: 1,
      livestreamEnabled: false,
      isFantasyEnabled: false,
      livestreamEnabledGeo: [],
      alertType: "",
      shortStatus: "KKR won",
      matchImageId: 379130,
    },
    venueInfo: {
      established: 1974,
      capacity: "33,000",
      knownAs: null,
      ends: "Garware Pavilion End, Tata End",
      city: "Mumbai",
      country: "India",
      timezone: "+05:30",
      homeTeam: "Mumbai, Mumbai Indians",
      floodlights: true,
      curator: "Sudhir Naik",
      profile:
        "<b>Introduction</b>:\n\nRelatively younger than old-world grounds like Chepauk, Eden Gardens and Feroz Shah Kotla, the Wankhede stadium has its own fair share of unforgettable memories attached to it. It has been home to some of the greatest cricketers to have played for the country. \n\n<b>Venue history</b>:\n\nMumbai has played host to Test matches at three different venues - the first ever Test in India was hosted at the Bombay Gymkhana in 1933-34 against England. After the second World War, Cricket Club of India's (CCI) Brabourne Stadium became the city's second ground. However, a dispute between the CCI and the Mumbai Cricket Association (MCA) over the allocation of tickets for cricket matches forced the latter to build a separate stadium. The stadium was named after the association's president Barrister Sheshrao Krishnarao Wankhede. The initial capacity of the stadium was around 45,000. The first Test was staged in the season of 1974-75 when West Indies toured India.\n\n<b>Venue description</b>:\n\nThe stadium has seven different stands - Sunil Gavaskar Stand, North Stand, Vijay Merchant Stand, Sachin Tendulkar Stand, MCA Pavilion, Divecha Pavilion, and Garware Pavilion.\n\nIn 1996, Wankhede stadium underwent an upgrade, during which, floodlights were installed to provide excellent lighting to host the day and night cricket matches. Wankhede received its second upgrade in 2010-11 before the 2011 World Cup and the ground was unavailable for domestic and international cricket until February 2011. One of the highlights of the stadium is the suspended cantilever roofs. No beam supports on the roofs ensure better view for the spectators. The stadium has 20 elevators for North and South stands. After its renovation and installation of bucket seats the capacity of the Wankhede Stadium was reduced to around 33,000.\n\n<b>How does the pitch play?</b>\n\nThe wicket at the Wankhede offers help for both the pacers and spinners. Close proximity to the Arabian sea helps the swing bowlers considerably, especially during early hours of the day. However, spinners have been known to benefit during the last couple of days of a Test match as the pitch turns into a vicious turner. Although the new ball does a bit in limited-overs cricket, the pitch tends to ease out and favour batsmen as the innings progresses. The venue provides great entertainment when it comes to T20 cricket.\n\n<b>Trivia</b>:\n\nBangladesh scored the lowest ODI total at the stadium. They were 115 all out, when it competed with India in the 1998 season.\n\nRavi Shastri's six sixes in an over off Baroda's Tilak Raj en route to the fastest double-hundred in first-class cricket was on this ground in 1984-85.\n\nby <b>Sonali Dhulap</b>",
      imageUrl:
        "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/81.jpg",
      ground: "Wankhede Stadium",
      groundLength: 0,
      groundWidth: 0,
      otherSports: null,
    },
    broadcastInfo: [],
  };

  const [matchData, setMatchData] = useState([]);

  async function matchdetail() {
    const url = `https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/${id}`;
    const options = {
      method: "GET",
      headers: {
        "x-rapidapi-key": "1b86a4dd70msh9fcf4f2263c1280p104ab7jsn224cd34ac589",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
      },
    };

    try {
      const response = await fetch(url, options);
      const result = await response.json();
      setMatchData(result);
      console.log(result);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    // matchdetail();
  }, []);
  return (
    <>
  
      {/* {matchData.length <= 0 ? (
        <h1>Loadding ......</h1>
      ) : ( */}
      <InPageNavigation
        teams={[fixeddata.matchInfo.team1.name, fixeddata.matchInfo.team2.name]}
      >
        {fixeddata.matchInfo.team1.playerDetails.map((data, i) => {
          return (
            <div key={i}>
              <h2>{data.fullName}</h2>
              <h3>{data.role}</h3>
            </div>
          );
        })}
        {fixeddata.matchInfo.team2.playerDetails.map((data, i) => {
          return (
            <div key={i}>
              <h2>{data.fullName}</h2>
              <h3>{data.role}</h3>
            </div>
          );
        })}
      </InPageNavigation>
      {/* )} */}
    </>
  );
}

export default MatchDetail;
